version: '3.7'

services:

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    #command: gunicorn myblog.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=@)3idi3^v=$$10)%jj@@un3+lfu-=y!uf3wy%tjectctx3#2i9e
      - DEBUG=0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    hostname: db
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: