# Generated by Django 3.1 on 2020-09-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200830_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('special_permission', 'Can read all posts')]},
        ),
    ]
